### ISSUE TITLE
failure to launch k8s cluster when ipv6 disabled

### ISSUE THREAD

**Issue by zbialik** [coreos/flannel-cni#14]
I am deploying a k8s cluster deployed using `Rancher v2.1.7` (backed by `flannel`)

I am trying to run `Kubernetes v1.11.8`, which uses the following flannel-relevant system images:
- `flannel: rancher/coreos-flannel:v0.10.0`
- `flannel_cni: rancher/coreos-flannel-cni:v0.3.0`

When I try to initialize a k8s cluster using flannel, I get a ton of pods failing to create with the following message from `kubectl describe pod ${POD_NAME}`:

`Warning  FailedCreatePodSandBox  1m (x4 over 1m)   kubelet, 10.15.2.240  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "12345678910" network for pod "kube-dns-123456-abc4y": NetworkPlugin cni failed to set up pod "kube-dns-123456-abc4y_kube-system" network: open /proc/sys/net/ipv6/conf/eth0/accept_dad: no such file or directory, failed to clean up sandbox container "12345678910" network for pod "kube-dns-123456-abc4y": NetworkPlugin cni failed to teardown pod "kube-dns-123456-abc4y_kube-system" network: failed to get IP addresses for "eth0": <nil>]`

I have ipv6 disabled on my k8s nodes and don't have problems booting up a k8s cluster with another network provider (like Calico).

When I enable ipv6, I am able to bootup the cluster. However I don't want to have to do this. 

I read that this issue was fixed in the latest release of containernetworking/plugins: v0.7.0
- [relevant issue notes](https://github.com/coreos/flannel/issues/936)
- [fix notes](https://github.com/containernetworking/plugins/pull/62)
- [release notes](https://github.com/containernetworking/plugins/compare/v0.6.0...v0.7.0)

Is this going to get supported in a new release of flannel-cni? Since I use rancher for my k8s cluster deployments, I have to pretty much rely on the implementation of the flannel-cni docker container.

**Comment by dghubble** [comment]
This project does not publish those images, rancher must be providing `rancher/coreos-flannel` and `rancher/coreos-flannel-cni`. Ask Rancher where the source code for their images resides and about debugging.

**Comment by zbialik** [comment]
ok i've posted on their issue board. Thank you.
